# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Dynamics of Partially Molten Rock
author: Frederico Teixeira & Richard F. Katz
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: -1

exclude_patterns: 
  - /_build/* 
  - /rock-env/*
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/FoaLab/partially-molten-rock-PUP  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax_config:
      TeX:
        equationNumbers: { autoNumber: "AMS" }
        Macros:
          "unit": ["{\\hat{#1}}", 1]
          "Curl": "{\\Grad\\!\\times}"
          "Da": "{\\textrm{Da}}"
          "DaII": "{\\textrm{Da}_{\\textrm{II}}}"
          "DaPe": "{\\textrm{DaPe}}"
          "Dh": "{\\Delta{h}}"
          "Div": "{\\Grad\\!\\cdot}"
          "Dt": "{\\Delta{t}}"
          "Dx": "{\\Delta{x}}"
          "Dy": "{\\Delta{y}}"
          "Dz": "{\\Delta{z}}"
          "Fmax": "{F_\\text{max}}"
          "Gibbs": "{G}"
          "Grad": ["{\\boldsymbol{\\nabla}}"]
          "Kk": "{\\mathcal{K}}"
          "LambertW": "{\\mathcal{W}}"
          "Pe": "{\\textrm{Pe}}"
          "Ra": "{\\textrm{Ra}}"
          "Thermoeq": ["{\\boldsymbol{\\Theta}}"]
          "act": "{a}"
          "activationE": "{E^*}"
          "activationV": "{V^*}"
          "actvec": ["{\\boldsymbol{\\act}}"]
          "adiprod": "{\\left.\\tfrac{\\infd{F}}{\\infd{z}}\\right\\vert_\\textrm{s}}"
          "affinity": "{\\Delta\\chempo}"
          "aprx": ["{\\tilde{#1}}", 1]
          "assembly": "{{\\mathlarger{\\mathlarger{\\mathscr{A}}}}}"
          "bandangle": "{\\theta}"
          "basis": "{\\mathcal{S}}"
          "biharm": "{\\nabla^4}"
          "boxmeltrate": "{\\mathcal{G}}"
          "bulkenthalpy": "{H}"
          "bulkvisc": "{\\zeta_\\phi}"
          "buoynumber": "{\\textrm{B}}"
          "cbasestate": "{\\mathcal{F}}"
          "chemdiffuse": "{\\mathcal{D}}"
          "chemdisperse": ["{\\tilde{\\boldsymbol{\\chemdiffuse}}}"]
          "chempo": "{\\mu}"
          "clapeyron": "{\\vartheta}"
          "cmp": "{\\mathcal{C}}"
          "cmpdisspar": "{\\Pi}"
          "cmpforce": "{F_\\manufac}"
          "cmplength": "{\\delta}"
          "cmppres": "{\\mathcal{\\pres}}"
          "cmpvel": "{\\vel^\\cmp}"
          "cmpvisc": "{\\xi_\\phi}"
          "cmpviscconst": "{C}"
          "coltime": ["{\\tau^\\text{col}_{#1}}", 1]
          "con": "{c}"
          "conductivity": "{k_\\energy}"
          "coninflow": "{\\con\\sol_0}"
          "cotwo": "{CO$_2${}}"
          "dFdT": "{\\mathcal{M}_F}"
          "ddecaymatrix": "{\\grave{\\decaymatrix}}"
          "decarrow": ["{\\overset{#1}{\\longrightarrow}}", 1]
          "decaymatrix": ["{\\boldsymbol{\\mathcal{L}}}"]
          "deco": "{\\lambda}"
          "delsq": "{\\nabla^2}"
          "density": "{\\rho}"
          "devstressten": ["{\\boldsymbol{\\tau}}"]
          "dico": "{D}"
          "dicoratio": "{\\dico^r}"
          "dicovec": ["{\\boldsymbol{\\dico}}"]
          "diff": ["{\\frac{\\textrm{d}{#1}}{\\textrm{d}{#2}}}", 2]
          "difftwo": ["{\\frac{\\textrm{d}^2{#1}}{\\textrm{d}{#2}^2}}", 2]
          "dihed": ["{\\Theta}"]
          "diracdelta": "{\\updelta}"
          "dissipation": "{\\Psi}"
          "dpro": "{\\mathcal{G}}"
          "drag": "{D}"
          "e": "{\\text{e}}"
          "effpres": "{\\cmppres^\\text{eff}}"
          "effstressten": "{\\obar{\\stressten}^\\text{eff}}"
          "effvel": ["{w^{\\dico_{#1}}}", 1]
          "effvelcon": ["{{w}^{\\dico_{#1}}_0}", 1]
          "efocus": "{E_F}"
          "eigenvecs": ["{\\boldsymbol{V}}"]
          "energy": "{e}"
          "enthalpy": "{h}"
          "entropy": "{\\textrm{s}}"
          "equi": ["{\\check{{#1}}}", 1]
          "equicon": "{\\equi{\\con}}"
          "error": "{E}"
          "expansivity": "{\\alpha}"
          "exrxn": "{\\mathcal{X}}"
          "first": "{^{(1)}}"
          "flux": ["{\\boldsymbol{J}}"]
          "fluxpar": "{\\mathcal{Q}}"
          "freezelength": "{\\delta_f}"
          "fullstrrten": ["{\\dot{\\boldsymbol{e}}}"]
          "fz": "{^{(1,z)}}"
          "gibbs": "{g}"
          "grainexp": "{\\mathfrak{m}}"
          "grainsize": "{d}"
          "gravity": ["{\\mathbf{g}}"]
          "growamp": "{s}"
          "growrate": "{\\dot{\\growamp}}"
          "halflife": "{\\tau^{(1/2)}}"
          "heatcapacity": "{c_\\pres}"
          "identity": ["{\\boldsymbol{I}}"]
          "inact": "{\\tilde{\\act}}"
          "indicate": "{\\Phi}"
          "infd": "{\\textrm{d}}"
          "infs": ["{\\textrm{d}\\boldsymbol{S}}"]
          "infv": "{\\textrm{d}^3\\microposvec}"
          "intarea": "{\\mathcal{A}}"
          "interface": "{\\mathcal{I}}"
          "interphase": "{\\mathbf{F}}"
          "intfc": "{^\\interface}"
          "isotp": ["{{^{#1}\\textrm{#2}}}", 2]
          "lagdiff": ["{\\frac{\\textrm{D}_{#1}{#2}}{\\textrm{D}{#3}}}", 3]
          "latent": "{L}"
          "layershear": "{\\mathcal{S}}"
          "layershearstress": "{\\mathcal{T}}"
          "layerstress": "{\\mathcal{F}}"
          "layerthick": "{\\mathcal{H}}"
          "liq": "{^\\liquid}"
          "liqslope": "{M^\\liquidus}"
          "liqsol": "{_{\\liquid\\solid}}"
          "liqtemp": "{\\temp^\\liquidus}"
          "liquid": "{\\ell}"
          "liquidus": "{\\mathcal{L}}"
          "liquidvisc": "{\\mu\\liq}"
          "lith": "{^\\text{lith}}"
          "lncon": "{C}"
          "manufac": "{\\text{mfc}}"
          "matlab": "{\\textsc{Matlab}}"
          "mckenzie": "{M\\textsuperscript{c}Kenzie}"
          "meangrainsize": "{\\langle{d}\\rangle}"
          "melt": "{^{\\Gamma}}"
          "meltregion": "{\\mathcal{Z}}"
          "melttemp": "{\\temp^m}"
          "mf": "{f}"
          "mgo": "{\\text{MgO}}"
          "mgol": "{{\\text{Mg}_2\\text{SiO}_4}}"
          "mgopx": "{{\\text{Mg}_2\\text{Si}_2\\text{O}_6}}"
          "micro": ["{\\breve{#1}}", 1]
          "microposvec": "{\\micro{\\posvec}}"
          "microvel": "{\\micro{\\vel}}"
          "mobility": "{K_\\phi}"
          "molarmass": "{M}"
          "molarparco": "{\\parco^{*}}"
          "molfrac": "{X}"
          "normalvec": ["{\\boldsymbol{n}}"]
          "npor": "{\\varphi}"
          "obar": ["{\\overline{#1}}", 1]
          "olivine": "{\\textrm{Ol}}"
          "omf": "{(1-\\mf)}"
          "omp": "{(1-\\por)}"
          "onsagermatrix": "{E}"
          "opx": "{\\textrm{Opx}}"
          "order": ["{\\mathcal{O}\\!\\left(#1\\right)}", 1]
          "parco": "{\\equi{\\parcod}}"
          "parcod": "{K}"
          "pdiff": ["{\\frac{\\partial{#1}}{\\partial{#2}}}", 2]
          "pdiffmix": ["{\\frac{\\partial^2{#1}}{\\partial{#2}\\partial{#3}}}", 3]
          "pdifftwo": ["{\\frac{\\partial^2{#1}}{\\partial{#2}^2}}", 2]
          "perm": "{k_\\phi}"
          "permexp": ["{n}"]
          "phasemolarmass": "{\\mathcal{M}}"
          "por": "{\\phi}"
          "pordisagg": "{\\phi_\\Xi}"
          "pormax": "{\\phi_\\text{max}}"
          "porweaken": "{\\lambda}"
          "posvec": ["{\\boldsymbol{x}}"]
          "potemp": "{\\temp_p}"
          "pres": "{P}"
          "pure": ["{\\mathring{{#1}}}", 1]
          "qtz": "{{\\text{SiO}_2}}"
          "radheat": "{\\mathcal{Q}}"
          "reynolds": "{\\text{Re}}"
          "rhat": ["{\\hat{\\boldsymbol{r}}}"]
          "rpro": "{\\mathcal{M}}"
          "rve": "{\\text{\\tiny RVE}}"
          "rxnrate": "{\\mathcal{R}}"
          "scalarpotential": "{\\mathcal{U}}"
          "scalarvel": "{v}"
          "scale": ["{\\left[{#1}\\right]}", 1]
          "second": "{^{(2)}}"
          "segflux": ["{\\boldsymbol{q}}"]
          "sfc": "{\\text{sfc}}"
          "sfce": "{\\gamma}"  # "sfce": "{\\upgamma}"
          "sfcten": "{\\tau}"
          "sfctenpar": "{\\mathcal{S}}"
          "sfctenvshear": "{\\text{D}_\\interface}"
          "shearstrainrate": "{\\dot{\\gamma}}"
          "shearvisc": "{\\eta_\\phi}"
          "smallpar": "{\\epsilon}"
          "sol": "{^\\solid}"
          "solid": "{s}"
          "solidus": "{\\mathcal{S}}"
          "solslope": "{M^\\solidus}"
          "solsol": "{_{\\solid\\solid}}"
          "soltemp": "{\\temp^\\solidus}"
          "solwave": "{\\Lambda}"
          "solwaveamp": "{\\solwave^*}"
          "solwavespeed": ["{\\upsilon}"]
          "stiff": "{\\mathcal{S}}"
          "stokesforce": ["{\\boldsymbol{G}_\\manufac}"]
          "strainrate": "{\\dot{\\varepsilon}}"
          "stressten": ["{\\boldsymbol{\\sigma}}"]
          "strrexp": "{\\mathfrak{n}}"
          "strrexpc": "{\\mathcal{N}}"
          "strrinv": ["{\\dot{\\varepsilon}_{II}}"]
          "strrten": ["{\\dot{\\boldsymbol{\\varepsilon}}}"]
          "temp": "{T}"
          "test": ["{\\hat{#1}}", 1]
          "testfunc": "{\\mathcal{W}}"
          "thermaldiffuse": "{\\kappa}"
          "thetahat": ["{\\hat{\\boldsymbol{\\theta}}}"]
          "tr": ["{\\text{trace\\,}}"]
          "traceexrate": "{r}"
          "transp": "{\\intercal}"
          "twonorm": ["{\\left\\vert\\left\\vert{#1}\\right\\vert\\right\\vert_2}", 1]
          "unitnormalvec": ["{\\hat{\\normalvec}}"]
          "usat": "{\\chi}"
          "vectorpotential": ["{\\boldsymbol{\\Psi}}"]
          "vel": ["{\\boldsymbol{\\scalarvel}}"]
          "velratio": "{v_r}"
          "viscratio": "{\\nu_\\phi}"
          "wavelength": ["{l}"]
          "wavenumber": "{k}"
          "wavevector": ["{\\boldsymbol{k}}"]
          "xfocus": "{\\Delta{x}_F}"
          "xhat": ["{\\hat{\\boldsymbol{x}}}"]
          "yhat": ["{\\hat{\\boldsymbol{y}}}"]
          "zeroth": "{^{(0)}}"
          "zhat": ["{\\hat{\\boldsymbol{z}}}"]
          "zpfte": "{\\left(\\bulkvisc+\\tfrac{4}{3}\\shearvisc\\right)}"

parse:
  myst_enable_extensions:
    # don"t forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
